---
- name: Start docker on boot
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
