global:
  scrape_interval: 30s
  external_labels:
    hydra_component: "floyd"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "ispmonitor"
    scrape_interval: 60s
    static_configs:
      - targets: ["100.94.241.54:9283"] # RPi telegraf Agent
