---
- name: check for installation...
  become: yes
  become_user: root
  stat:
    path: '{{ influxdb_install_dir }}'
  changed_when: False
  register: influxdb_binary
- when: not influxdb_binary.stat.exists
  block:
    - name: download
      become: yes
      become_user: root
      get_url:
        url: '{{ influxdb_tgz_url }}'
        dest: /tmp/{{ influxdb_tgz }}
        checksum: '{{ influxdb_checksum }}'
    - name: unarchive
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ influxdb_tgz }}
        dest: '{{ influxdb_install_parent_dir }}'
        creates: '{{ influxdb_install_dir }}'
  always:
    - name: cleanup...
      become: yes
      become_user: root
      file:
        path: /tmp/{{ influxdb_tgz }}
        state: absent
- name: link
  become: yes
  become_user: root
  file:
    src: '{{ influxdb_install_dir }}'
    dest: '{{ influxdb_link_dir }}'
    state: link

- name: add to default profile.d
  become: yes
  become_user: root
  with_items:
    - f: influxdb.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'
- when: influxdb_config is defined
  include_tasks: configure.yml
