---
- name: Enable tailscaled service
  ansible.builtin.service:
    name: tailscaled
    state: started
    enabled: true

- name: Tailscale Status
  listen: Confirm Tailscale is Connected
  ansible.builtin.command: tailscale status
  register: handlers_tailscale_status

- name: Assert Tailscale is Connected
  listen: Confirm Tailscale is Connected
  ansible.builtin.assert:
    that:
      - handlers_tailscale_status.stdout | length != 0
