---
- name: Deploy InfluxDB
  hosts: all
  become: true

  tasks:
    - name: Add InfluxDB APT GPG key
      ansible.builtin.apt_key:
        url: https://repos.influxdata.com/influxdb.key

    - name: Add InfluxDB APT repository
      ansible.builtin.apt_repository:
        repo: deb https://repos.influxdata.com/ubuntu focal stable
        state: present

    - name: Install InfluxDB
      ansible.builtin.apt:
        name: influxdb
        state: present

    - name: Start and enable InfluxDB service
      ansible.builtin.systemd:
        name: influxdb
        enabled: true
        state: started

    - name: Wait for InfluxDB to start
      ansible.builtin.wait_for:
        port: 8086
        delay: 5
        timeout: 60

    - name: Create InfluxDB admin user and database
      community.general.influxdb_database:
        host: localhost
        username: root
        password: your_influxdb_password
        database_name: your_database_name
        state: present

    - name: Create a regular user for InfluxDB
      community.general.influxdb_user:
        host: localhost
        username: root
        password: your_influxdb_password
        database_name: your_database_name
        user_name: your_user_name
        user_password: your_user_password
        state: present
