---
- name: Install Salt Minion
  hosts: all
  become: yes
  tasks:
    - name: Install Salt Minion package
      apt:
        name: salt-minion
        state: present
    - name: Start and enable Salt Minion service
      service:
        name: salt-minion
        state: started
        enabled: yes
    - name: Configure Salt Minion
      template:
        src: minion.j2
        dest: /etc/salt/minion
