---

- hosts: all
  roles:
    - role: bootstrap-node
      tags:
        - bootstrap

    - role: setup-docker
      become: true
      tags:
        - docker
    
    - role: setup-tailscale
      become: yes
      tags:
        - tailscale
      roles:

    - role: setup-influxdb
      become: yes
      tags:
        - influxdb

    - role: andrewrothstein.influxdb
      become: yes
      tags:
        - andrewrothstein_influxdb

    - role: andrewrothstein.influxdb2
      become: yes
      tags:
        - andrewrothstein_influxdb2

      # influxdb_orgs:
      #   - name: main-org
      #     description: Main organization
      #   - name: guest-org

      # influxdb_users:
      #   - name: admin01
      #     org: main-org
      #     password: secretPassword
      #   - name: guest01
      #     org: guest-org
      #     password: secretPassword

      # influxdb_buckets:
      #   - name: bucket01
      #     description: First bucket
      #     org: main-org
      #     retention: 1d
      #   - name: bucket02
      #     org: main-org



    # - role: viasite-ansible.zsh
    #   become: yes
    #   tags:
    #     - zsh
